# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 53f21b5
_src_path: git@github.com:MeteoSwiss-APN/mch-python-blueprint.git
email: simon.adamov@meteoswiss.ch
full_name: Simon Adamov
github_username: MeteoSwiss-APN
module_name: neural_lam
project_doc_url: https://github.io/MeteoSwiss-APN/neural-lam
project_github: https://github.com/MeteoSwiss-APN/neural-lam
project_keywords: numericalweatherpredictions
project_name: Neural-LAM
project_short_description: Neural Weather Prediction for Limited Area Modeling
project_slug: neural-lam
project_ssh_url: git+ssh://git@github.com/MeteoSwiss-APN/neural-lam.git
python_version: '3.10'
version: 0.1.0
year: '2023'
