name: neural-ddp
channels:
  - pytorch
  - nvidia
  - pyg
dependencies:
  - Cartopy
  - ipython
  - matplotlib
  - networkx
  - numpy
  - pip
  - plotly
  - pyproj
  - pytorch
  - pytorch-cuda=11.8
  - pyg
  - pytorch-lightning
  - scikit-learn
  - scipy
  - shapely
  - torchaudio
  - torchvision
  - wandb
  - xarray
  - pip:
    - tueplots
